import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { briefText, contactUrl, decisions, firstGap, nextGaps, phaseCopy, scopeSignal } from '../app.js';

const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const css = await readFile(new URL('../styles.css', import.meta.url), 'utf8');
assert.match(html, /<title>Website &amp; Web App Rebuild Scope Planner \| Evolved Designs<\/title>/);
assert.match(html, /utm_content=hero_service_path#web-development-services/);

assert.equal(decisions.length, 16);
assert.equal(scopeSignal([]).band, 'discovery');
assert.equal(scopeSignal(decisions.slice(0, 5).map(([key]) => key)).band, 'definition');
assert.equal(scopeSignal(decisions.map(([key]) => key)).band, 'acceptance');
assert.match(firstGap(['content']), /highest-value public journeys/);
assert.equal(nextGaps(['content']).length, 3);
assert.match(nextGaps(['content'])[0], /highest-value public journeys/);
assert.match(phaseCopy([]).heading, /inventory/);
assert.match(contactUrl('replace', []), /replace_discovery/);
assert.doesNotMatch(contactUrl('replace', ['security']), /security/);
assert.match(briefText('consolidate', []), /not a price estimate/);
assert.equal((html.match(/<link rel="canonical"/g) ?? []).length, 1);
assert.equal((html.match(/type="radio"/g) ?? []).length, 3);
assert.equal((html.match(/type="checkbox"/g) ?? []).length, 16);
assert.match(html, /Search discovery handoff/);
assert.match(html, /Indexability and discovery/);
assert.match(html, /utm_content=search_discovery_path/);
assert.match(html, /developers\.google\.com\/search\/docs\/crawling-indexing\/block-indexing/);
assert.match(html, /developers\.google\.com\/search\/docs\/crawling-indexing\/links-crawlable/);
assert.match(html, /WCAG22\/Techniques\/general\/G91/);
assert.match(html, /Design-to-build handoff/);
assert.match(html, /Content stewardship/);
assert.match(html, /idahoaeyc\.org\/careers\/rfp-idaho-aeyc-website-redevelopment/);
assert.match(html, /data-gaps/);
assert.match(html, /ohsu\.edu\/procurement\/bids/);
assert.match(html, /WCAG 2\.2 AA/);
assert.match(html, /section508\.gov\/buy/);
assert.match(html, /OWASA RFP 27-001/);
assert.match(html, /Selections stay in this browser/);
assert.match(html, /web-development\/\?utm_source=github/);
assert.match(html, /service_path#web-development-services/);
assert.match(html, /Masterwork Music and Art Foundation/);
assert.match(html, /utm_content=arts_foundation_path/);
assert.match(html, /Protect the private path/);
assert.match(html, /masterworkarts\.blogspot\.com\/2026\/08\/web-site-redesign-request-for-proposal\.html/);
assert.match(html, /Event and ticketing websites/);
assert.match(html, /Choose the ticket model/);
assert.match(html, /utm_content=event_ticketing_path/);
assert.match(html, /docs\.stripe\.com\/payments\/checkout/);
assert.match(html, /WCAG22\/Understanding\/target-size-minimum\.html/);
assert.match(html, /Visual portfolio and studio websites/);
assert.match(html, /utm_content=visual_portfolio_path/);
assert.match(html, /developers\.google\.com\/search\/docs\/appearance\/google-images/);
assert.match(html, /w3\.org\/WAI\/tutorials\/images/);
assert.match(html, /responsive sources, dimensions, formats/);
assert.match(html, /Portal and matching platforms/);
assert.match(html, /Identity and account lifecycle/);
assert.match(html, /Matching and recommendation rules/);
assert.match(html, /utm_content=portal_matching_path/);
assert.match(html, /lsntap\.org\/jobs-rfps\/request-proposal-web-development-consultant/);
assert.match(html, /accessible-authentication-minimum\.html/);
assert.match(html, /Mobile app to web product/);
assert.match(html, /Cross-platform continuity/);
assert.match(html, /utm_content=app_to_web_continuity_path/);
assert.match(html, /reactnative\.dev\/docs\/native-platform/);
assert.match(html, /nextjs\.org\/docs\/app\/guides\/production-checklist/);
assert.match(html, /w3\.org\/WAI\/standards-guidelines\/mobile/);
assert.doesNotMatch(html + css, /clarity\.ms|Microsoft Clarity/i);
assert.match(css, /prefers-reduced-motion/);

const structured = html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
assert.ok(structured);
assert.deepEqual(JSON.parse(structured[1])['@graph'].map((item) => item['@type']), ['WebApplication', 'FAQPage']);
console.log('Public website rebuild scope planner checks passed.');
